# Generated by Django 3.0.4 on 2020-04-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_organisation',
            name='name',
        ),
        migrations.AlterField(
            model_name='category_organisation',
            name='id',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Medical'), (2, 'Administrative'), (3, 'Logistics')], default=0, primary_key=True, serialize=False),
        ),
    ]
