# Generated by Django 3.0.4 on 2020-04-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20200409_1249'),
        ('organisation_category', '0002_auto_20200409_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Organisation',
            new_name='Organisation_Category',
        ),
    ]
