# Generated by Django 3.0.4 on 2020-04-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0002_auto_20200408_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField()),
                ('justification', models.TextField()),
                ('recommendation', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('consent', models.BooleanField(default=False)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.BooleanField(choices=[(0, 'Female'), (1, 'Male')], default=0)),
                ('country', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('assigned_partners', models.ManyToManyField(blank=True, related_name='assigned_cases', to='organisation.Organisation')),
                ('matched_partners', models.ManyToManyField(blank=True, related_name='matched_cases', to='organisation.Organisation')),
            ],
        ),
    ]
