# Generated by Django 3.0.4 on 2020-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField()),
                ('justification', models.TextField()),
                ('recommendation', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('consent', models.BooleanField(default=False)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.BooleanField(choices=[('0', 'Female'), ('1', 'Male')], default=0)),
                ('country', models.CharField(max_length=150)),
                ('comments', models.TextField()),
                ('outcome', models.CharField(max_length=160)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('assigned_partners', models.CharField(max_length=100)),
                ('matched_partners', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
