# Generated by Django 3.0.4 on 2020-04-10 13:33

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField()),
                ('justification', models.TextField()),
                ('recommendation', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('consent', models.BooleanField(default=False)),
                ('age', models.CharField(max_length=50)),
                ('sex', models.BooleanField(choices=[(0, 'Female'), (1, 'Male')], default=0)),
                ('country', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='created', name='CaseWorkflow', states=['created', 'validated', 'closed', 'rejected']))),
                ('assigned_partners', models.ManyToManyField(blank=True, related_name='assigned_cases', to='organisations.Organisation')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
    ]
