# Generated by Django 3.0.4 on 2020-04-09 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20200408_2314'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_partners',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_cases', to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='matched_partners',
            field=models.ManyToManyField(blank=True, null=True, related_name='matched_cases', to='organisation.Organisation'),
        ),
    ]
