# Generated by Django 3.0.4 on 2020-04-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200410_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('validate', 'Can validate cases'), ('close', 'Can close cases'), ('reject', 'Can reject cases'), ('assign_organizations', 'Can assign a case to a matched and accepted organization'), ('match_organizations', 'Can match organizations to cases')]},
        ),
    ]
