# Generated by Django 3.0.4 on 2020-04-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200411_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('validate_case', 'Can validate cases'), ('close_case', 'Can close cases'), ('reject_case', 'Can reject cases'), ('assign_organizations', 'Can assign a case to a matched and accepted organization'), ('match_organizations', 'Can match organizations to cases')]},
        ),
    ]
