# Generated by Django 3.0.4 on 2020-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20200408_2314'),
        ('cases', '0004_auto_20200409_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assigned_partners',
            field=models.ManyToManyField(blank=True, related_name='assigned_cases', to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='case',
            name='matched_partners',
            field=models.ManyToManyField(blank=True, related_name='matched_cases', to='organisation.Organisation'),
        ),
    ]
