# Generated by Django 3.0.4 on 2020-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('categories', '0004_auto_20200410_1537'),
        ('cases', '0005_auto_20200411_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accepted_partners',
            field=models.ManyToManyField(blank=True, related_name='accepted_cases', to='organisations.Organisation'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ManyToManyField(default=0, related_name='cases', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=10),
        ),
    ]
