# Generated by Django 3.0.4 on 2020-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200411_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=10),
        ),
    ]
