# Generated by Django 3.0.4 on 2020-04-09 20:56

from django.db import migrations
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200409_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='created', name='CaseWorkflow', states=['created', 'validated', 'matched', 'assigned', 'closed', 'rejected'])),
        ),
    ]
