# Generated by Django 3.0.4 on 2020-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200410_1537'),
        ('cases', '0006_auto_20200413_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ManyToManyField(default=0, related_name='cases', to='categories.Category'),
        ),
    ]
