# Generated by Django 3.0.4 on 2020-04-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('cases', '0006_auto_20200413_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accepted_partners',
            field=models.ManyToManyField(blank=True, related_name='accepted_cases', to='organisations.Organisation'),
        ),
    ]
