# Generated by Django 3.0.4 on 2020-04-16 08:26

from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200415_1801'),
        ('cases', '0006_auto_20200415_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='case',
            name='accepted_partners',
        ),
        migrations.RemoveField(
            model_name='case',
            name='assigned_partners',
        ),
        migrations.RemoveField(
            model_name='case',
            name='matched_partners',
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='matched', name='PartnerWorkflow', states=['matched', 'accepted', 'assigned', 'rejected']))),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnered_organisations', to='cases.Case')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnered_cases', to='organisations.Organisation')),
            ],
            options={
                'unique_together': {('case', 'organisation')},
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.AddField(
            model_name='case',
            name='organisations',
            field=models.ManyToManyField(blank=True, through='cases.Partnership', to='organisations.Organisation'),
        ),
    ]
