# Generated by Django 3.0.4 on 2020-04-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20200415_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='category',
            new_name='categories',
        ),
    ]
