# Generated by Django 3.0.4 on 2020-04-15 13:18

from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('cases', '0007_auto_20200415_0938'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='case',
        #     name='accepted_partners',
        # ),
        # migrations.RemoveField(
        #     model_name='case',
        #     name='assigned_partners',
        # ),
        # migrations.RemoveField(
        #     model_name='case',
        #     name='matched_partners',
        # ),
        migrations.CreateModel(
            name='PartneredOrganisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='matched', name='PartnerWorkflow', states=['matched', 'accepted', 'assigned', 'rejected']))),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnered_organisations', to='cases.Case')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnered_cases', to='organisations.Organisation')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
        migrations.AddField(
            model_name='case',
            name='organisations',
            field=models.ManyToManyField(blank=True, through='cases.PartneredOrganisations', to='organisations.Organisation'),
        ),
    ]
