# Generated by Django 3.0.4 on 2020-04-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200409_1700'),
        ('cases', '0007_auto_20200409_2338'),
    ]

    operations = [
    ]
