# Generated by Django 3.0.4 on 2020-04-17 12:26

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20200416_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Emergency', 'Emergency'), ('Life Changing', 'Life Changing'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Surgical Care', 'Surgical Care'), ('Air Transportation', 'Air Transportation'), ('Accommodation Support', 'Accommodation Support'), ('Financial Support', 'Financial Support')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='Created', name='CaseWorkflow', states=['Created', 'Open', 'Closed', 'Rejected'])),
        ),
    ]
