# Generated by Django 3.0.4 on 2020-04-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('cases', '0008_auto_20200415_1404'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='case',
        #     name='accepted_partners',
        # ),
        # migrations.RemoveField(
        #     model_name='case',
        #     name='assigned_partners',
        # ),
        # migrations.RemoveField(
        #     model_name='case',
        #     name='matched_partners',
        # ),
        migrations.AlterUniqueTogether(
            name='partneredorganisations',
            unique_together={('case', 'organisation')},
        ),
    ]
