# Generated by Django 3.0.4 on 2020-04-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20200417_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='tags',
        ),
    ]
