# Generated by Django 3.0.4 on 2020-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200410_1537'),
        ('cases', '0011_remove_case_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('validate_case', 'Can validate cases'), ('close_case', 'Can close cases'), ('reject_case', 'Can reject cases'), ('assign_organisations', 'Can assign a case to a matched and accepted organisation'), ('match_organisations', 'Can match organisations to cases'), ('update_match', 'Can set a matched partnership to accepted/rejected'), ('view_dashboard', 'Can look at the dashboard to see statistics and insights.')]},
        ),
        migrations.AlterField(
            model_name='case',
            name='categories',
            field=models.ManyToManyField(related_name='cases', to='categories.Category'),
        ),
    ]
