# Generated by Django 3.0.4 on 2020-04-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20200418_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='current_treatment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='history_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='investigations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='nature_of_referral',
            field=models.CharField(choices=[('Life changing', 'Life changing'), ('Emergency', 'Emergency'), ('Urgent', 'Urgent')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='past_medical_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='physical_examination',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='age',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='recommendation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
