# Generated by Django 3.0.4 on 2020-04-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20200418_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='nature_of_referral',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Life changing', 'Life changing'), ('Urgent', 'Urgent')], default='', max_length=20),
        ),
    ]
