# Generated by Django 3.0.4 on 2020-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20200418_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('validate_case', 'Can validate cases'), ('close_case', 'Can close cases'), ('reject_case', 'Can reject cases'), ('assign_organisations', 'Can assign a case to a matched and accepted organisation'), ('match_organisations', 'Can match organisations to cases'), ('update_match', 'Can set a matched partnership to accepted/rejected'), ('view_general_info', 'Can view general information about a case'), ('update_general_info', 'Can update general information about a case'), ('view_medical_info', 'Can view medical information about a case')]},
        ),
        migrations.RemoveField(
            model_name='case',
            name='comments',
        ),
        migrations.AlterField(
            model_name='case',
            name='nature_of_referral',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Life changing', 'Life changing')], default='', max_length=20),
        ),
    ]
