# Generated by Django 3.0.4 on 2020-04-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20200419_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='nature_of_referral',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Life changing', 'Life changing'), ('Urgent', 'Urgent')], default='', max_length=20),
        ),
    ]
