# Generated by Django 3.0.4 on 2020-04-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20200419_1604'),
        ('cases', '0025_auto_20200419_2115'),
    ]

    operations = [
    ]
