# Generated by Django 3.0.4 on 2020-04-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_merge_20200420_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='nature_of_referral',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Life changing', 'Life changing')], default='Emergency', max_length=20),
        ),
    ]
