# Generated by Django 3.0.4 on 2020-04-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_auto_20200420_1323'),
        ('cases', '0028_auto_20200420_1548'),
    ]

    operations = [
    ]
