# Generated by Django 3.0.4 on 2020-04-21 22:01

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200410_1537'),
        ('cases', '0030_auto_20200421_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cases', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='requested', name='CaseWorkflow', states=['requested', 'open', 'closed', 'rejected'])),
        ),
    ]
