# Generated by Django 3.0.4 on 2020-04-22 22:21

from django.db import migrations, models
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_auto_20200421_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closing_reason',
            field=models.IntegerField(choices=[(0, 'Success/Transfer Accepted'), (1, 'Patient died'), (2, 'Not fulfilling criteria'), (3, 'No Partner Organisation found'), (4, 'Other')], default=4),
        ),
        migrations.AlterField(
            model_name='case',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=django_xworkflows.models.StateField(max_length=16, workflow=django_xworkflows.models._SerializedWorkflow(initial_state='requested', name='CaseWorkflow', states=['requested', 'open', 'closed', 'rejected'])),
        ),
    ]
