# Generated by Django 3.0.4 on 2020-04-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_auto_20200422_2221'),
        ('cases', '0031_auto_20200422_1604'),
    ]

    operations = [
    ]
