# Generated by Django 3.0.4 on 2020-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Medical'), (2, 'Administrative'), (3, 'Logistics')], default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
