# Generated by Django 3.0.4 on 2020-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200410_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Medical'), (2, 'Administrative'), (3, 'Logistics')], default=0, primary_key=True, serialize=False),
        ),
    ]
