# Generated by Django 3.0.4 on 2020-04-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200410_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='id',
        ),
    ]
