# Generated by Django 3.0.4 on 2020-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cases_created',
            field=models.CharField(max_length=200, null=True, verbose_name='cases_created'),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.CharField(max_length=200, null=True, verbose_name='organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(max_length=200, null=True, verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='last name'),
        ),
    ]
