# Generated by Django 3.0.4 on 2020-04-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200407_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cases_created',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='first name'),
        ),
    ]
