# Generated by Django 3.0.4 on 2020-04-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_remove_organisation_members'),
        ('users', '0002_auto_20200416_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='organisations.Organisation'),
        ),
    ]
