# Generated by Django 3.0.4 on 2020-04-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('services', models.TextField(max_length=500)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('members', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='categories.Category')),
            ],
        ),
    ]
