# Generated by Django 3.0.4 on 2020-04-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200410_1537'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='category',
        ),
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.ManyToManyField(default=0, related_name='organisations', to='categories.Category'),
        ),
    ]
