# Generated by Django 3.0.4 on 2020-04-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200415_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='category',
            new_name='categories',
        ),
    ]
