# Generated by Django 3.0.4 on 2020-04-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200415_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='members',
        ),
    ]
