# Generated by Django 3.0.4 on 2020-04-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200418_1125'),
        ('organisations', '0005_auto_20200419_1604'),
    ]

    operations = [
    ]
