# Generated by Django 3.0.4 on 2020-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('services', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('M', 'Medical'), ('A', 'Administrative'), ('L', 'Logistics')], max_length=1)),
                ('tag', models.CharField(max_length=100)),
                ('accept', models.BooleanField(blank=True, null=True)),
                ('assigned_cases', models.CharField(max_length=100, null=True)),
                ('matched_cases', models.CharField(max_length=100, null=True)),
                ('members', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
