# Generated by Django 3.0.4 on 2020-04-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='assigned_cases',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='matched_cases',
        ),
    ]
