# Generated by Django 3.0.4 on 2020-04-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_category', '0001_initial'),
        ('organisation', '0002_auto_20200408_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='organisation_category.Category_Organisation'),
        ),
    ]
