# Generated by Django 3.0.4 on 2020-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20200409_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='accept',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='members',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
