# Generated by Django 3.0.4 on 2020-04-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_auto_20200419_2101'),
        ('comments', '0002_auto_20200419_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='case',
            field=models.ManyToManyField(blank=True, related_name='comments', to='cases.Case'),
        ),
    ]
