# Generated by Django 3.0.4 on 2020-04-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_auto_20200419_2115'),
        ('comments', '0003_auto_20200419_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='case',
        ),
        migrations.AddField(
            model_name='comment',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.Case'),
        ),
    ]
